import { chromium } from "playwright";
const browser = await chromium.launch({ args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const errors = [];
page.on("pageerror", (e) => errors.push(String(e)));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
await page.goto("http://127.0.0.1:8080/", { waitUntil: "networkidle" });
await page.getByRole("button", { name: "New hunt" }).click();
await page.locator("text=You are No. 47").click();
await page.getByRole("button", { name: /Dovra/ }).click();
await page.getByRole("button", { name: "Begin hunt" }).click();
await page.waitForTimeout(500);
await page.getByRole("button", { name: /^Guard/ }).click();
await page.waitForTimeout(300);
let t = await page.locator("body").innerText();
console.log("after guard AP line:\n", t.match(/AP .*/)?.[0], "\nlog snippet:", t.includes("knits") || t.includes("Guard") || t.includes("blade") ? "has log" : t.split("\n").filter(l=>l.includes("Kira")||l.includes("blade")||l.includes("Guard")).slice(0,8));
await page.screenshot({ path: "/workspace/screenshots/combat-guard.png" });
await page.getByRole("button", { name: "Wait" }).click();
await page.waitForTimeout(400);
t = await page.locator("body").innerText();
console.log("after wait:\n", t.slice(0, 450));
await page.screenshot({ path: "/workspace/screenshots/combat-wait.png" });
// mobile title
await page.goto("http://127.0.0.1:8080/", { waitUntil: "networkidle" });
await page.setViewportSize({ width: 390, height: 844 });
await page.waitForTimeout(400);
await page.screenshot({ path: "/workspace/screenshots/title-mobile.png" });
console.log("errors", errors);
await browser.close();
