//! Series roster, skills, island, hunts.

use crate::combat::{Attr, ShapeKind, Side, SkillDef, Stats, UnitTemplate};
use crate::hex::Axial;

pub fn skill(id: &str) -> Option<&'static SkillDef> {
    SKILLS.iter().find(|s| s.id == id)
}

pub fn warrior(id: &str) -> Option<&'static UnitTemplate> {
    WARRIORS.iter().find(|u| u.id == id)
}

pub fn enemy(id: &str) -> Option<&'static UnitTemplate> {
    ENEMIES.iter().find(|u| u.id == id)
}

pub fn location(id: &str) -> Option<&'static LocationDef> {
    LOCATIONS.iter().find(|l| l.id == id)
}

pub fn encounter(id: &str) -> Option<&'static EncounterDef> {
    ENCOUNTERS.iter().find(|e| e.id == id)
}

pub fn derived(stats: &Stats) -> Derived {
    Derived {
        hit: stats.a + stats.c,
        dodge: stats.a + stats.p + stats.w,
        r#move: (stats.a / 3).max(2),
        yoki: 8 + stats.w * 4,
        strikes: (stats.a / 4).max(1),
    }
}

#[derive(Clone, Copy, Debug)]
pub struct Derived {
    pub hit: i32,
    pub dodge: i32,
    pub r#move: i32,
    pub yoki: i32,
    pub strikes: i32,
}

#[derive(Clone, Copy, Debug)]
pub struct LocationDef {
    pub id: &'static str,
    pub name: &'static str,
    pub region: &'static str,
    pub blurb: &'static str,
    pub x: f32,
    pub y: f32,
    pub kind: &'static str,
    pub encounter: Option<&'static str>,
    pub deadline: i32,
    pub art: &'static str,
}

#[derive(Clone, Copy, Debug)]
pub struct EnemySpawn {
    pub template: &'static str,
    pub origin: Axial,
    pub facing: i32,
}

#[derive(Clone, Copy, Debug)]
pub struct EncounterDef {
    pub id: &'static str,
    pub title: &'static str,
    pub briefing: &'static str,
    pub art: &'static str,
    pub cols: i32,
    pub rows: i32,
    pub enemies: &'static [EnemySpawn],
    pub player_origins: &'static [Axial],
    pub karma: i32,
    pub rank: i32,
    pub recruit: &'static [&'static str],
    pub raki: bool,
    pub flag: &'static str,
}

const fn sk(
    id: &'static str,
    name: &'static str,
    blurb: &'static str,
    ap: i32,
    trans: i32,
    yoki: i32,
    shape: ShapeKind,
    range: i32,
    pa: Attr,
    pd: Attr,
    power: i32,
) -> SkillDef {
    SkillDef {
        id,
        name,
        blurb,
        ap,
        trans,
        yoki,
        shape,
        range,
        length: range,
        pa,
        pd,
        power,
        aimed: false,
        self_cast: false,
        heal: 0,
        trans_delta: 0,
        r#move: 0,
        guard: 0,
        telegraph: false,
        afterimage: false,
        unblockable: false,
        strikes: false,
    }
}

pub static SKILLS: &[SkillDef] = &[
    SkillDef {
        aimed: false,
        self_cast: false,
        heal: 0,
        trans_delta: 0,
        r#move: 0,
        guard: 0,
        telegraph: false,
        afterimage: false,
        unblockable: false,
        strikes: false,
        length: 1,
        ..sk(
            "cut",
            "Cut",
            "A clean greatsword line.",
            1,
            0,
            0,
            ShapeKind::Single,
            1,
            Attr::S,
            Attr::A,
            18,
        )
    },
    SkillDef {
        aimed: true,
        ..sk(
            "aimed",
            "Aimed Cut",
            "Trade certainty for a limb.",
            1,
            20,
            4,
            ShapeKind::Single,
            1,
            Attr::C,
            Attr::A,
            16,
        )
    },
    SkillDef {
        self_cast: true,
        guard: 3,
        ..sk(
            "guard",
            "Guard",
            "Blade up.",
            1,
            0,
            0,
            ShapeKind::SelfCast,
            0,
            Attr::C,
            Attr::S,
            0,
        )
    },
    SkillDef {
        self_cast: true,
        r#move: 2,
        ..sk(
            "vault",
            "Vault",
            "Leave the hex.",
            1,
            20,
            3,
            ShapeKind::Leap,
            2,
            Attr::A,
            Attr::A,
            0,
        )
    },
    SkillDef {
        self_cast: true,
        heal: 22,
        ..sk(
            "knit",
            "Heal",
            "Force meat back together.",
            1,
            20,
            6,
            ShapeKind::SelfCast,
            0,
            Attr::W,
            Attr::S,
            0,
        )
    },
    SkillDef {
        self_cast: true,
        heal: 8,
        trans_delta: -12,
        ..sk(
            "rest",
            "Rest",
            "Lower the bar.",
            2,
            0,
            0,
            ShapeKind::SelfCast,
            0,
            Attr::C,
            Attr::C,
            0,
        )
    },
    SkillDef {
        self_cast: true,
        trans_delta: -28,
        ..sk(
            "drop",
            "Trans Drop",
            "A human hand on your wrist.",
            1,
            0,
            0,
            ShapeKind::SelfCast,
            0,
            Attr::C,
            Attr::C,
            0,
        )
    },
    SkillDef {
        ..sk(
            "lure",
            "Lure",
            "A boy in the open. The yoma turns.",
            1,
            0,
            0,
            ShapeKind::Single,
            4,
            Attr::P,
            Attr::P,
            0,
        )
    },
    SkillDef {
        self_cast: true,
        telegraph: true,
        ..sk(
            "read",
            "Yoki Sense",
            "See the next swing.",
            1,
            20,
            5,
            ShapeKind::SelfCast,
            0,
            Attr::P,
            Attr::C,
            0,
        )
    },
    SkillDef {
        strikes: true,
        guard: 2,
        ..sk(
            "flash",
            "Quicksword",
            "Too fast to see.",
            1,
            40,
            10,
            ShapeKind::Sweep,
            1,
            Attr::A,
            Attr::A,
            14,
        )
    },
    SkillDef {
        length: 3,
        ..sk(
            "wind",
            "Windcutter",
            "Draw, cut, sheath.",
            1,
            40,
            8,
            ShapeKind::Line,
            3,
            Attr::C,
            Attr::A,
            20,
        )
    },
    SkillDef {
        length: 4,
        ..sk(
            "stretch",
            "Stretching",
            "The arm leaves the shoulder.",
            1,
            40,
            8,
            ShapeKind::Line,
            4,
            Attr::S,
            Attr::A,
            17,
        )
    },
    SkillDef {
        self_cast: true,
        r#move: 3,
        afterimage: true,
        ..sk(
            "phantom",
            "Phantom",
            "You are already gone.",
            1,
            40,
            8,
            ShapeKind::Leap,
            3,
            Attr::A,
            Attr::P,
            0,
        )
    },
    SkillDef {
        unblockable: true,
        ..sk(
            "spiral",
            "Drill Sword",
            "Twenty-one turns in the shoulder.",
            2,
            60,
            14,
            ShapeKind::Single,
            1,
            Attr::S,
            Attr::S,
            38,
        )
    },
    SkillDef {
        self_cast: true,
        heal: 40,
        ..sk(
            "regen",
            "Regeneration",
            "A lost arm is an argument she wins.",
            1,
            40,
            12,
            ShapeKind::SelfCast,
            0,
            Attr::W,
            Attr::S,
            0,
        )
    },
    sk(
        "claw",
        "Rend",
        "A yoma's only thesis.",
        1,
        0,
        0,
        ShapeKind::Single,
        1,
        Attr::S,
        Attr::A,
        16,
    ),
    SkillDef {
        length: 2,
        ..sk(
            "lunge",
            "Lunge",
            "Too many joints.",
            1,
            20,
            0,
            ShapeKind::Line,
            2,
            Attr::A,
            Attr::A,
            14,
        )
    },
    sk(
        "ripple",
        "Ripple Blade",
        "A ring of cutting air. It grows.",
        2,
        40,
        8,
        ShapeKind::Ripple,
        0,
        Attr::S,
        Attr::A,
        18,
    ),
    sk(
        "slam",
        "Core Slam",
        "The body falls on three hexes.",
        1,
        20,
        0,
        ShapeKind::Blast,
        1,
        Attr::S,
        Attr::S,
        20,
    ),
    SkillDef {
        length: 3,
        ..sk(
            "whip",
            "Tail Whip",
            "The tail is the weapon.",
            1,
            0,
            0,
            ShapeKind::Line,
            3,
            Attr::S,
            Attr::A,
            15,
        )
    },
];

const fn unit(
    id: &'static str,
    name: &'static str,
    title: &'static str,
    rank: i32,
    side: Side,
    portrait: &'static str,
    sprite: &'static str,
    stats: Stats,
    skills: &'static [&'static str],
    trans: i32,
    color: [f32; 3],
    hp: i32,
) -> UnitTemplate {
    UnitTemplate {
        id,
        name,
        title,
        rank,
        side,
        portrait,
        sprite,
        stats,
        skills,
        trans,
        footprint: &[Axial { q: 0, r: 0 }],
        core_index: 0,
        parts: &[],
        body_hp: hp,
        color,
    }
}

pub static WARRIORS: &[UnitTemplate] = &[
    unit(
        "clare",
        "Clare",
        "No. 47",
        47,
        Side::Player,
        "art/clare.jpg",
        "sprites/clare.png",
        Stats {
            s: 6,
            a: 8,
            c: 9,
            p: 11,
            w: 7,
        },
        &[
            "cut", "aimed", "guard", "read", "flash", "wind", "knit", "rest", "drop",
        ],
        8,
        [0.78, 0.80, 0.83],
        48,
    ),
    unit(
        "raki",
        "Raki",
        "The boy from Doga",
        0,
        Side::Player,
        "art/raki.jpg",
        "art/raki.jpg",
        Stats {
            s: 2,
            a: 4,
            c: 3,
            p: 5,
            w: 3,
        },
        &["lure"],
        0,
        [0.62, 0.48, 0.36],
        16,
    ),
    unit(
        "miria",
        "Miria",
        "No. 6 · Phantom",
        6,
        Side::Player,
        "art/miria.jpg",
        "sprites/miria.png",
        Stats {
            s: 8,
            a: 12,
            c: 10,
            p: 9,
            w: 8,
        },
        &["cut", "guard", "phantom", "aimed", "rest"],
        18,
        [0.60, 0.64, 0.68],
        62,
    ),
    unit(
        "helen",
        "Helen",
        "No. 22 · Stretching",
        22,
        Side::Player,
        "art/helen.jpg",
        "sprites/helen.png",
        Stats {
            s: 10,
            a: 8,
            c: 7,
            p: 7,
            w: 6,
        },
        &["cut", "stretch", "guard", "rest"],
        22,
        [0.72, 0.64, 0.54],
        70,
    ),
    unit(
        "deneve",
        "Deneve",
        "No. 15 · Regeneration",
        15,
        Side::Player,
        "art/deneve.jpg",
        "sprites/deneve.png",
        Stats {
            s: 11,
            a: 6,
            c: 11,
            p: 6,
            w: 8,
        },
        &["cut", "guard", "regen", "knit", "rest"],
        16,
        [0.55, 0.58, 0.56],
        88,
    ),
];

pub static ENEMIES: &[UnitTemplate] = &[
    unit(
        "yoma",
        "Yoma",
        "Flesh-eater",
        0,
        Side::Enemy,
        "sprites/yoma.png",
        "sprites/yoma.png",
        Stats {
            s: 7,
            a: 6,
            c: 3,
            p: 5,
            w: 2,
        },
        &["claw", "lunge"],
        35,
        [0.54, 0.23, 0.20],
        36,
    ),
    unit(
        "yoma_stretch",
        "Long Yoma",
        "Jointed",
        0,
        Side::Enemy,
        "sprites/yoma.png",
        "sprites/yoma.png",
        Stats {
            s: 8,
            a: 7,
            c: 4,
            p: 6,
            w: 3,
        },
        &["claw", "stretch"],
        48,
        [0.48, 0.18, 0.16],
        44,
    ),
    UnitTemplate {
        id: "ophelia",
        name: "Ophelia",
        title: "Awakened No. 4 · Ripple",
        rank: 4,
        side: Side::Enemy,
        portrait: "art/ophelia.jpg",
        sprite: "sprites/ophelia.png",
        stats: Stats {
            s: 13,
            a: 10,
            c: 8,
            p: 8,
            w: 6,
        },
        skills: &["ripple", "claw", "slam"],
        trans: 88,
        footprint: &[
            Axial { q: 0, r: 0 },
            Axial { q: 1, r: 0 },
            Axial { q: 2, r: 0 },
            Axial { q: 0, r: -1 },
        ],
        core_index: 0,
        parts: &[
            ("core", "Core", 0, 70, None),
            ("torso", "Torso", 1, 40, None),
            ("tail", "Tail", 2, 32, Some("ripple")),
            ("arm", "Cutting Arm", 3, 28, Some("claw")),
        ],
        body_hp: 0,
        color: [0.85, 0.82, 0.77],
    },
    UnitTemplate {
        id: "worm",
        name: "Awakened Worm",
        title: "Northern Campaign · 5 cells",
        rank: 0,
        side: Side::Enemy,
        portrait: "sprites/worm.png",
        sprite: "sprites/worm.png",
        stats: Stats {
            s: 14,
            a: 6,
            c: 5,
            p: 5,
            w: 4,
        },
        skills: &["whip", "slam", "claw"],
        trans: 80,
        footprint: &[
            Axial { q: 0, r: 0 },
            Axial { q: 1, r: 0 },
            Axial { q: 2, r: 0 },
            Axial { q: 3, r: 0 },
            Axial { q: 4, r: 0 },
        ],
        core_index: 0,
        parts: &[
            ("core", "Head", 0, 55, None),
            ("n1", "Neck", 1, 30, None),
            ("n2", "Thorax", 2, 30, None),
            ("n3", "Trunk", 3, 26, None),
            ("tail", "Tail", 4, 24, Some("whip")),
        ],
        body_hp: 0,
        color: [0.81, 0.78, 0.69],
    },
];

pub static LOCATIONS: &[LocationDef] = &[
    LocationDef {
        id: "doga",
        name: "Doga",
        region: "Lautrec",
        blurb: "Mud, goats, a well. Something has been wearing the neighbors.",
        x: 0.28,
        y: 0.58,
        kind: "village",
        encounter: Some("doga-yoma"),
        deadline: 36,
        art: "art/tavern.jpg",
    },
    LocationDef {
        id: "stora",
        name: "Stora",
        region: "Lautrec",
        blurb: "A market that pretends the Organization is a weather report.",
        x: 0.36,
        y: 0.66,
        kind: "village",
        encounter: None,
        deadline: 0,
        art: "art/tavern.jpg",
    },
    LocationDef {
        id: "hanel",
        name: "Hanel",
        region: "Lautrec",
        blurb: "Statues of Teresa of the Faint Smile.",
        x: 0.33,
        y: 0.48,
        kind: "city",
        encounter: None,
        deadline: 0,
        art: "art/town-hanel.jpg",
    },
    LocationDef {
        id: "shire",
        name: "Mount Shire",
        region: "Alfons",
        blurb: "A shrine in the wind.",
        x: 0.5,
        y: 0.32,
        kind: "shrine",
        encounter: None,
        deadline: 0,
        art: "art/town-shire.jpg",
    },
    LocationDef {
        id: "paburo",
        name: "Paburo",
        region: "Highlands",
        blurb: "Joints in the trees. The nest has learned to reach.",
        x: 0.5,
        y: 0.46,
        kind: "wild",
        encounter: Some("paburo-nest"),
        deadline: 72,
        art: "art/battle-paburo.jpg",
    },
    LocationDef {
        id: "lacroa",
        name: "Lacroa",
        region: "Toulouse",
        blurb: "Search parties. They write your number down.",
        x: 0.62,
        y: 0.5,
        kind: "village",
        encounter: None,
        deadline: 0,
        art: "art/tavern.jpg",
    },
    LocationDef {
        id: "gonal",
        name: "Gonal",
        region: "Mucha",
        blurb: "A road town that asked for No. 4.",
        x: 0.5,
        y: 0.72,
        kind: "village",
        encounter: Some("gonal-ripple"),
        deadline: 96,
        art: "art/battle-gonal.jpg",
    },
    LocationDef {
        id: "pieta",
        name: "Pieta",
        region: "Alfons",
        blurb: "The north is gathering. Highest rank leads.",
        x: 0.48,
        y: 0.2,
        kind: "city",
        encounter: Some("pieta-worm"),
        deadline: 140,
        art: "art/town-pieta.jpg",
    },
    LocationDef {
        id: "maw",
        name: "Witch's Maw",
        region: "Lautrec",
        blurb: "Mount Zakol. Something older than a rank.",
        x: 0.18,
        y: 0.4,
        kind: "keep",
        encounter: None,
        deadline: 0,
        art: "art/town-maw.jpg",
    },
    LocationDef {
        id: "sutafu",
        name: "Sutafu",
        region: "East",
        blurb: "The Organization. Rank, orders, the brand.",
        x: 0.78,
        y: 0.48,
        kind: "office",
        encounter: None,
        deadline: 0,
        art: "art/town-sutafu.jpg",
    },
];

pub static ENCOUNTERS: &[EncounterDef] = &[
    EncounterDef {
        id: "doga-yoma", title: "Doga · the well",
        briefing: "Two of them wore neighbors yesterday. A cut is enough. Raise the bar if you must. Do not max it.",
        art: "art/battle-doga.jpg", cols: 11, rows: 8,
        enemies: &[EnemySpawn { template: "yoma", origin: Axial { q: 6, r: 2 }, facing: 3 }, EnemySpawn { template: "yoma", origin: Axial { q: 8, r: 5 }, facing: 3 }],
        player_origins: &[Axial { q: 2, r: 4 }, Axial { q: 1, r: 3 }, Axial { q: 1, r: 5 }],
        karma: 8, rank: 0, recruit: &[], raki: true, flag: "doga-cleared",
    },
    EncounterDef {
        id: "doga-nest", title: "Doga · the cellars",
        briefing: "The beacon went dark. No villagers. Three of them live in the well now.",
        art: "art/battle-doga.jpg", cols: 11, rows: 8,
        enemies: &[
            EnemySpawn { template: "yoma", origin: Axial { q: 6, r: 2 }, facing: 3 },
            EnemySpawn { template: "yoma", origin: Axial { q: 8, r: 5 }, facing: 3 },
            EnemySpawn { template: "yoma", origin: Axial { q: 7, r: 4 }, facing: 3 },
        ],
        player_origins: &[Axial { q: 2, r: 4 }, Axial { q: 1, r: 3 }, Axial { q: 1, r: 5 }],
        karma: 6, rank: 0, recruit: &[], raki: false, flag: "doga-cleared",
    },
    EncounterDef {
        id: "paburo-nest", title: "Paburo · the nest",
        briefing: "Miria is already here. Stay out of the long lines.",
        art: "art/battle-paburo.jpg", cols: 11, rows: 9,
        enemies: &[
            EnemySpawn { template: "yoma", origin: Axial { q: 7, r: 2 }, facing: 3 },
            EnemySpawn { template: "yoma", origin: Axial { q: 9, r: 6 }, facing: 3 },
            EnemySpawn { template: "yoma_stretch", origin: Axial { q: 8, r: 4 }, facing: 3 },
        ],
        player_origins: &[Axial { q: 1, r: 4 }, Axial { q: 2, r: 2 }, Axial { q: 2, r: 6 }],
        karma: 10, rank: -4, recruit: &["miria", "helen"], raki: false, flag: "paburo-cleared",
    },
    EncounterDef {
        id: "gonal-ripple", title: "Gonal · Ophelia",
        briefing: "Ophelia is four hexes of wrong anatomy. Cut the arm. Cut the tail.",
        art: "art/battle-gonal.jpg", cols: 12, rows: 9,
        enemies: &[EnemySpawn { template: "ophelia", origin: Axial { q: 7, r: 4 }, facing: 3 }],
        player_origins: &[Axial { q: 2, r: 3 }, Axial { q: 1, r: 5 }, Axial { q: 3, r: 6 }],
        karma: 16, rank: -8, recruit: &[], raki: false, flag: "gonal-cleared",
    },
    EncounterDef {
        id: "pieta-worm", title: "Pieta · the north",
        briefing: "Deneve will not die. The worm occupies five cells. Sever the tail.",
        art: "art/battle-pieta.jpg", cols: 13, rows: 10,
        enemies: &[
            EnemySpawn { template: "worm", origin: Axial { q: 7, r: 3 }, facing: 3 },
            EnemySpawn { template: "yoma", origin: Axial { q: 10, r: 7 }, facing: 3 },
        ],
        player_origins: &[Axial { q: 2, r: 4 }, Axial { q: 1, r: 6 }, Axial { q: 3, r: 7 }],
        karma: 20, rank: -6, recruit: &["deneve"], raki: false, flag: "pieta-cleared",
    },
];

pub const INTRO: &str = "You are Clare, No. 47.\n\nThe Organization branded you, ranked you, and sent you to the island to cut the things that wear human skin.\n\nDoga has lit a beacon. Walk there. Do not raise the bar unless you must.";
